# btc-box docker image

# Debian
FROM debian:latest

ENV btclocalbinurl=https://github.com/frz-dev/bitcoin-local/files/1647338/bitcoin-local-0.12.1-bin.tar.gz
ENV datadir=btc-data
ENV bindir=bin

RUN apt-get update
RUN apt-get install --yes net-tools dnsutils tcpdump
# dnsutils -> nslookup
# netcat   -> nc

# set working directory
#COPY ./$bindir/btc-0.15 /root/$bindir
RUN wget $btclocalbinurl && tar -zxvf *.tar.gz
COPY ./$datadir /root/$datadir

RUN ln -s /root/$bindir/* /usr/local/bin

# Create aliases
ENV btccli="bitcoin-cli -datadir=$datadir"
RUN echo "alias btc-cli='$btccli'" >> ~/.bashrc \
 && echo "alias getpeers='$btccli getpeerinfo'" >> ~/.bashrc \
 && echo "alias getblockcount='$btccli getblockcount'" >> ~/.bashrc \
 && echo "alias getlog='cat $datadir/debug.log'" >> ~/.bashrc \
 && echo "alias getpeersaddr='getpeers | grep addr'" >> ~/.bashrc \
 && echo "alias btcstart='bitcoind -datadir=$datadir -onlynet=ipv4 -debug -logips -daemon'" >> ~/.bashrc \
 && echo "alias btcstop='$btccli stop'" >> ~/.bashrc

WORKDIR /root/

# Expose Bitcoin ports
EXPOSE 8333 8332

ENTRYPOINT bitcoind -datadir=$datadir -debug -logips -daemon && /bin/bash
