# bitcoin-local-box docker image - Testnet

# Debian
FROM debian:latest

RUN apt-get update
RUN apt-get install --yes net-tools dnsutils wget bc
# dnsutils  -> nslookup
# netcat    -> nc

# Local ENV
ENV btcbinurl=https://github.com/frz-dev/bitcoin-local/raw/0.12.0-local/bin
ENV btcdir=/btc
ENV datadir=data
ENV bindir=bin
ENV btcnet=testnet3

# set working directory
RUN mkdir $btcdir
WORKDIR $btcdir

#RUN wget $btclocalbinurl && tar -zxvf *.tar.gz && rm *.tar.gz
RUN mkdir $datadir
COPY ./$datadir/bitcoin.conf-testnet-miner $datadir/bitcoin.conf

#COPY ./$bindir $bindir
RUN mkdir $bindir \
 && wget -O $bindir/bitcoind $btcbinurl/bitcoind \
 && wget -O $bindir/bitcoin-cli $btcbinurl/bitcoin-cli \
 && chmod +x $bindir/bitcoind $bindir/bitcoin-cli

RUN ln -s /btc/$bindir/bitcoind /usr/local/bin/bitcoind
RUN ln -s /btc/$bindir/bitcoin-cli /usr/local/bin/bitcoin-cli

#COPY ./btc-run.sh ./

# Create aliases
ENV btccli="bitcoin-cli -datadir=$btcdir/$datadir"
RUN printf "\
alias btc-cli='$btccli'\n\
alias getpeers='$btccli getpeerinfo'\n\
alias getblockcount='$btccli getblockcount'\n\
alias getlog='cat $datadir/$btcnet/debug.log'\n\
alias getpeersaddr='getpeers | grep addr'\n\
alias btcstart='bitcoind -datadir=$datadir -onlynet=ipv4 -debug -logips -daemon'\n\
alias btcstop='$btccli stop'\n\
" >> ~/.bashrc

# Expose Bitcoin ports
EXPOSE 18333 18332

# First line clears the DNS nameserver, imported at runtime by docker
# Then run bitcoin and start mining
ENTRYPOINT echo "nameserver 127.0.0.11" > /etc/resolv.conf \
  && bitcoind -datadir=$datadir -logips
