# bitcoin-local-box docker image - Testnet

# Debian
FROM debian:latest

ENV btclocalbinurl=https://github.com/frz-dev/bitcoin-local/files/1647338/bitcoin-local-0.12.1-bin.tar.gz
ENV datadir=data
ENV bindir=bin
ENV btcnet=testnet3

RUN apt-get update
RUN apt-get install --yes net-tools dnsutils wget
# dnsutils  -> nslookup
# netcat    -> nc

# set working directory
RUN mkdir btc
WORKDIR btc

#RUN wget $btclocalbinurl && tar -zxvf *.tar.gz && rm *.tar.gz
#RUN mkdir $datadir
COPY ./$bindir $bindir
COPY ./$datadir/bitcoin.conf-testnet $datadir/bitcoin.conf

RUN ln -s /btc/$bindir/bitcoind /usr/local/bin/bitcoind
RUN ln -s /btc/$bindir/bitcoin-cli /usr/local/bin/bitcoin-cli

# Create aliases
ENV btccli="bitcoin-cli -datadir=$datadir"
RUN echo "alias btc-cli='$btccli'" >> ~/.bashrc \
 && echo "alias getpeers='$btccli getpeerinfo'" >> ~/.bashrc \
 && echo "alias getblockcount='$btccli getblockcount'" >> ~/.bashrc \
 && echo "alias getlog='cat $datadir/$btcnet/debug.log'" >> ~/.bashrc \
 && echo "alias getpeersaddr='getpeers | grep addr'" >> ~/.bashrc \
 && echo "alias btcstart='bitcoind -datadir=$datadir -onlynet=ipv4 -debug -logips -daemon'" >> ~/.bashrc \
 && echo "alias btcstop='$btccli stop'" >> ~/.bashrc


# Expose Bitcoin ports
EXPOSE 18333 18332

# First line clears the DNS nameserver, imported at runtime by docker
ENTRYPOINT echo "nameserver 127.0.0.11" > /etc/resolv.conf \
  && bitcoind -datadir=$datadir -debug -logips -daemon \
  && /bin/bash
