# btc-box docker image
# bitcoin-version=0.15

# Debian
FROM debian:latest

ENV datadir=btc-data
ENV bindir=btc-bin

RUN apt-get update
RUN apt-get install --yes net-tools dnsutils tcpdump
# dnsutils -> nslookup
# netcat   -> nc

# set working directory
COPY ./$bindir /root/$bindir
COPY ./$datadir /root/$datadir

RUN ln -s /root/$bindir/* /usr/local/bin

ENV btccli="bitcoin-cli -datadir=$datadir"
RUN echo "alias btc-cli='$btccli'" >> ~/.bashrc \
 && echo "alias getpeers='$btccli getpeerinfo'" >> ~/.bashrc \
 && echo "alias getblockcount='$btccli getblockcount'" >> ~/.bashrc \
 && echo "alias getdebuglog='cat $datadir/debug.log'" >> ~/.bashrc \
 && echo "alias getpeersaddr='getpeers | grep addr'" >> ~/.bashrc \
 && echo "alias btcstart='bitcoind -datadir=$datadir -onlynet=ipv4 -debug -logips -daemon'" >> ~/.bashrc \
 && echo "alias btcstop='$btccli stop'" >> ~/.bashrc

WORKDIR /root/

# Expose Bitcoin ports
EXPOSE 8333 8332

ENTRYPOINT bitcoind -datadir=$datadir -debug -logips -daemon && /bin/bash
