# btc-dns-box (sipa) docker image

# Debian
FROM ubuntu:latest

# add bitcoind from the official PPA
RUN apt-get update \
 && apt-get install rsyslog tcpdump

# Create command 'dnsdebug'
RUN echo "alias dnsdebug='tcpdump  -vvv -s 0 -l port 53'" >> ~/.bashrc

# Set up BIND9
COPY ./sipa /root/sipa

WORKDIR /root/

EXPOSE 53/udp 53/tcp

ENTRYPOINT service rsyslog start \
  && /bin/bash
  #&& /root/ \
